# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f3e2d1e5358363743d3825693c4ca797eb7664b58f1b6b19bf65072208cfebe8faeaa45830b43b168e7ec0369213e2b8296c09e9d49d32c07bbe3b900b0660

test:
  secret_key_base: d43d5e3c2f4615aec71c97cb47728ccc935c9fdaa8712b76f4a0ab912284df1b20e3570bf2eb6c094a4fa6e5d7f3236caedcb39637a706a08e06ceb15506bc59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
